#!/bin/sh

system_type=$(uname -s)

setup_oh_my_zsh() {
    if [ ! -d "$HOME/.oh-my-zsh" ]; then
        echo "Setting up 'Oh My Zsh'"
        sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
    fi
}

setup_rust() {
    if [ ! -d "$HOME/.cargo" ]; then
        echo "Setting up 'Rust'"
        sh -c "$(curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs)" -a --default-toolchain nightly
    fi
}

if [ "$system_type" = "Linux" ]; then
    # Setup linux stuff here
    echo "Setting up 'Linux'"
fi

if [ "$system_type" = "Darwin" ]; then
    # Setup MacOS stuff here
    echo "Setting up 'MacOS'"
fi

setup_oh_my_zsh
setup_rust
